### PR TITLE
Enhance HTML generated by the shortcode

### PR DESCRIPTION
**Pull request by carstingaxion**
Ola @MatzeKitt,

I really like your plugin. Thanks for your work!

The only problem for me (personally) was the kinda poor html, that was rendered by the shortcode. So I suggest this as an improvement, to markup and styles. 

The added styles make sure, the new markup will not destroy the presentation in existing setups.

*I've read your contribution guidelines, after I made my changes and opened this PR. Hopefully you can have a look at it, even when we didn't had a first chat on this topic inside a created issue. Sorry for missing this.*

---

With this changes applied, you could drop the shortcode into a columns container and immidiately get something nice:

```
<div style="columns:4 200px">
[embed_privacy_opt_out]
</div>
```

220224_embed-privacy-columns

### CODE REVIEW

**Comment by MatzeKitt** [comment]
Hi @carstingaxion,

thank you for taking time to adjust that. In fact, the output could be better, but I don’t think an `<ol>` is semantically correct here. We should go with a `<ul>` here.

Additionally, since the `<li>` is a block-level element, it should be added to the output in a single line:
```
$output .= '<li>';
```

The same goes to the closing tag.

And last but not least, please check your code style while adding the check for empty headline and subline. Besides missing spaces, please check for non-empty and return content by default and an empty string else.

Best regards,
Matthias

**Comment by MatzeKitt** [comment]
Closing since there has been no feedback.

**Comment by carstingaxion** [comment]
Dear @MatzeKitt this was really not the nicest way to start.

I'm sorry, that I forgot about this totally and got thrilled down to reality as I saw your mentioning 6 weeks ago.
If you're open to, I would like to re-open this *topic* and go into further discussion with you and other contributors.

Best regards 
Carsten

**Comment by carstingaxion** [comment]
:+1:  Wow, this was fast.
I'm writing more details right now.

**Comment by carstingaxion** [comment]
Panic!

What happened here?
Why did *I* close this PR, and how?
And why did I force-pushed `main` on your repo?

This is absolutely weird to me and I would appreciate any help @MatzeKitt

**Comment by MatzeKitt** [comment]
I don’t know what action led to this. Maybe you updated your fork and accidentally used a force-push to get the current version? 🤷🏻‍♂️

**Comment by carstingaxion** [comment]
1. Within my local repo, I created a new branch with my changes from this PR
2. I used the *Syncronize* Button within Githubs UI from my repo. The little infobox said, syncronizing will discard my 2 commits, which was ok for me, because I created my local branch
3. I updated my local repo to the now syncronized aka updated `origin/main` of my repo

I can't get the point where this (could have) led to any changed on your side. Absolutely no clue ....

**Comment by carstingaxion** [comment]
I think I might have entered a new level of personal git curiosity here and **I'm seriously sorry**

Do theese 2 commits, that don't belong to any branch, affect your work ?

**Comment by MatzeKitt** [comment]
No, nothing on my project is changed. This is not possible due to the set project permissions. The `main` branch that was forced pushed to was your own inside your fork.

**Pull request closed without merging**
